"""
Each new term in the Fibonacci sequence is generated by adding
the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""


def fibonacci(n):
    prev_item = 0
    next_item = 1
    if n < 1:
        return 1
    else:
        for i in range(2, n + 2):
            prev_item, next_item = next_item, prev_item + next_item
    return next_item

#print(fibonacci(10))

num = 1
limit = 4000000
even_valued_sum = 0
while fibonacci(num) < limit:
    if fibonacci(num)%2 != 0:
        even_valued_sum += fibonacci(num)
    num += 1

print(even_valued_sum)

#4613731

    
        
    
        
